# Generated by Django 2.1.3 on 2021-04-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_calc', '0003_auto_20210425_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('is_current', models.CharField(max_length=100)),
                ('type_of_report', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user_with_data',
            name='diseases_with_dis_report',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
