# Generated by Django 2.1.3 on 2021-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_calc', '0004_auto_20210426_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='disease_type',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
